import React from 'react' ;

export default class Links extends React.Component {
    constructor(){
        super();

    }

    render(){
        var SCGlinks = []
        {for(var i = 0; i < 261; i++){
            SCGlinks.push(<a href={`http://sales.starcitygames.com//spoiler/display.php?&lang%5B%5D=1&r_all=All&g%5BG1%5D=NM/M&sort1=4&sort2=1&sort3=10&numpage=200&display=3&startnum=${i*200}`}> {i*200}</a>)
        }}

        var TCGlinks = []
        {for(var i = 0; i < TCGLinksOptions.length; i++){
            TCGlinks.push(<div><a href={`http://shop.tcgplayer.com/price-guide/magic/${TCGLinksOptions[i].link}`}>{TCGLinksOptions[i].name}</a></div>)
        }}


        return(
            <div className="linksComponent">
                {/*{SCGlinks.map(link=>link)}*/}
                {TCGlinks.map(link=>link)}
            </div>
        );
    }
}

var TCGLinksOptions =    [
    {link : "hour-of-devastation", name : "Hour of Devastation"},
    // {link : "archenemy-nicol-bolas", name : "Archenemy: Nicol Bolas"},
    // {link : "commander-anthology", name : "Commander Anthology"},
    // {link : "amonkhet", name : "Amonkhet"},
    // {link : "masterpiece-series-amonkhet-invocations", name : "Masterpiece Series: Amonkhet Invocations"},
    // {link : "welcome-deck-2017", name : "Welcome Deck 2017"},
    // {link : "duel-decks-mind-vs-might", name : "Duel Decks: Mind vs. Might"},
    // {link : "modern-masters-2017", name : "Modern Masters 2017"},
    // {link : "aether-revolt", name : "Aether Revolt"},
    // {link : "planechase-anthology", name : "Planechase Anthology"},
    // {link : "commander-2016", name : "Commander 2016"},
    // {link : "kaladesh", name : "Kaladesh"},
    // {link : "masterpiece-series-kaladesh-inventions", name : "Masterpiece Series: Kaladesh Inventions"},
    // {link : "duel-decks-nissa-vs-ob-nixilis", name : "Duel Decks: Nissa vs. Ob Nixilis"},
    // {link : "conspiracy-take-the-crown", name : "Conspiracy: Take the Crown"},
    // {link : "from-the-vault-lore", name : "From the Vault: Lore"},
    // {link : "wmcq-promo-cards", name : "WMCQ Promo Cards"},
    // {link : "eldritch-moon", name : "Eldritch Moon"},
    // {link : "eternal-masters", name : "Eternal Masters"},
    // {link : "shadows-over-innistrad", name : "Shadows over Innistrad"},
    // {link : "welcome-deck-2016", name : "Welcome Deck 2016"},
    // {link : "duel-decks-blessed-vs-cursed", name : "Duel Decks: Blessed vs. Cursed"},
    // {link : "oath-of-the-gatewatch", name : "Oath of the Gatewatch"},
    // {link : "commander-2015", name : "Commander 2015"},
    // {link : "battle-for-zendikar", name : "Battle for Zendikar"},
    // {link : "zendikar-expeditions", name : "Zendikar Expeditions"},
    // {link : "duel-decks-zendikar-vs-eldrazi", name : "Duel Decks: Zendikar vs. Eldrazi"},
    // {link : "from-the-vault-angels", name : "From the Vault: Angels"},
    // {link : "magic-origins", name : "Magic Origins"},
    // {link : "modern-masters-2015", name : "Modern Masters 2015"},
    // {link : "dragons-of-tarkir", name : "Dragons of Tarkir"},
    // {link : "tarkir-dragonfury-promos", name : "Tarkir Dragonfury Promos"},
    // {link : "duel-decks-elspeth-vs-kiora", name : "Duel Decks: Elspeth vs. Kiora"},
    // {link : "fate-reforged", name : "Fate Reforged"},
    // {link : "ugins-fate-promos", name : "Ugin's Fate Promos"},
    // {link : "duel-decks-anthology", name : "Duel Decks: Anthology"},
    // {link : "commander-2014", name : "Commander 2014"},
    // {link : "khans-of-tarkir", name : "Khans of Tarkir"},
    // {link : "magic-2015-m15", name : "Magic 2015 (M15)"},
    // {link : "journey-into-nyx", name : "Journey Into Nyx"},
    // {link : "theros", name : "Theros"},
    // {link : "heros-path-promos", name : "Hero's Path Promos"},
    // {link : "gatecrash", name : "Gatecrash"},
    // {link : "return-to-ravnica", name : "Return to Ravnica"},
    // {link : "scars-of-mirrodin", name : "Scars of Mirrodin"},
    // {link : "magic-2011-m11", name : "Magic 2011 (M11)"},
    // {link : "archenemy", name : "Archenemy"},
    // {link : "rise-of-the-eldrazi", name : "Rise of the Eldrazi"},
    // {link : "worldwake", name : "Worldwake"},
    // {link : "zendikar", name : "Zendikar"},
    // {link : "magic-2010-m10", name : "Magic 2010 (M10)"},
    // {link : "duels-of-the-planeswalkers", name : "Duels of the Planeswalkers"},
    // {link : "alara-reborn", name : "Alara Reborn"},
    // {link : "conflux", name : "Conflux"},
    // {link : "shards-of-alara", name : "Shards of Alara"},
    // {link : "eventide", name : "Eventide"},
    // {link : "shadowmoor", name : "Shadowmoor"},
    // {link : "morningtide", name : "Morningtide"},
    // {link : "wpn-and-gateway-promos", name : "WPN &amp; Gateway Promos"},
    // {link : "lorwyn", name : "Lorwyn"},
    // {link : "game-day-promos", name : "Game Day Promos"},
    // {link : "10th-edition", name : "10th Edition"},
    // {link : "future-sight", name : "Future Sight"},
    // {link : "grand-prix-promos", name : "Grand Prix Promos"},
    // {link : "planar-chaos", name : "Planar Chaos"},
    // {link : "special-occasion", name : "Special Occasion"},
    // {link : "pro-tour-promos", name : "Pro Tour Promos"},
    // {link : "time-spiral", name : "Time Spiral"},
    // {link : "timeshifted", name : "Timeshifted"},
    // {link : "coldsnap", name : "Coldsnap"},
    // {link : "coldsnap-theme-deck-reprints", name : "Coldsnap Theme Deck Reprints"},
    // {link : "dissension", name : "Dissension"},
    // {link : "champs-promos", name : "Champs Promos"},
    // {link : "guildpact", name : "Guildpact"},
    // {link : "magic-premiere-shop", name : "Magic Premiere Shop"},
    // {link : "ravnica", name : "Ravnica"},
    // {link : "9th-edition", name : "9th Edition"},
    // {link : "saviors-of-kamigawa", name : "Saviors of Kamigawa"},
    // {link : "betrayers-of-kamigawa", name : "Betrayers of Kamigawa"},
    // {link : "unhinged", name : "Unhinged"},
    // {link : "champions-of-kamigawa", name : "Champions of Kamigawa"},
    // {link : "fifth-dawn", name : "Fifth Dawn"},
    // {link : "darksteel", name : "Darksteel"},
    // {link : "mirrodin", name : "Mirrodin"},
    // {link : "launch-party-and-release-event-promos", name : "Launch Party &amp; Release Event Promos"},
    // {link : "scourge", name : "Scourge"},
    // {link : "8th-edition", name : "8th Edition"},
    // {link : "legions", name : "Legions"},
    // {link : "onslaught", name : "Onslaught"},
    // {link : "judgment", name : "Judgment"},
    // {link : "torment", name : "Torment"},
    // {link : "oversize-cards", name : "Oversize Cards"},
    // {link : "odyssey", name : "Odyssey"},
    // {link : "apocalypse", name : "Apocalypse"},
    // {link : "magic-player-rewards", name : "Magic Player Rewards"},
    // {link : "7th-edition", name : "7th Edition"},
    // {link : "planeshift", name : "Planeshift"},
    // {link : "invasion", name : "Invasion"},
    // {link : "prophecy", name : "Prophecy"},
    // {link : "starter-2000", name : "Starter 2000"},
    // {link : "nemesis", name : "Nemesis"},
    // {link : "european-lands", name : "European Lands"},
    // {link : "fnm-promos", name : "FNM Promos"},
    // {link : "mercadian-masques", name : "Mercadian Masques"},
    // {link : "guru-lands", name : "Guru Lands"},
    // {link : "unique-and-miscellaneous-promos", name : "Unique and Miscellaneous Promos"},
    // {link : "jss-mss-promos", name : "JSS/MSS Promos"},
    // {link : "judge-promos", name : "Judge Promos"},
    // {link : "urzas-destiny", name : "Urza's Destiny"},
    // {link : "portal-three-kingdoms", name : "Portal Three Kingdoms"},
    // {link : "classic-sixth-edition", name : "Classic Sixth Edition"},
    // {link : "starter-1999", name : "Starter 1999"},
    // {link : "urzas-legacy", name : "Urza's Legacy"},
    // {link : "media-promos", name : "Media Promos"},
    // {link : "anthologies", name : "Anthologies"},
    // {link : "urzas-saga", name : "Urza's Saga"},
    // {link : "apac-lands", name : "APAC Lands"},
    // {link : "unglued", name : "Unglued"},
    // {link : "exodus", name : "Exodus"},
    // {link : "portal-second-age", name : "Portal Second Age"},
    // {link : "stronghold", name : "Stronghold"},
    // {link : "tempest", name : "Tempest"},
    // {link : "prerelease-cards", name : "Prerelease Cards"},
    // {link : "weatherlight", name : "Weatherlight"},
    // {link : "portal", name : "Portal"},
    // {link : "vanguard", name : "Vanguard"},
    // {link : "fifth-edition", name : "Fifth Edition"},
    // {link : "visions", name : "Visions"},
    // {link : "mirage", name : "Mirage"},
    // {link : "arena-promos", name : "Arena Promos"},
    // {link : "alliances", name : "Alliances"},
    // {link : "homelands", name : "Homelands"},
    // {link : "ice-age", name : "Ice Age"},
    // {link : "chronicles", name : "Chronicles"},
    // {link : "fourth-edition", name : "Fourth Edition"},
    // {link : "fallen-empires", name : "Fallen Empires"},
    // {link : "the-dark", name : "The Dark"},
    // {link : "legends", name : "Legends"},
    // {link : "revised-edition", name : "Revised Edition"},
    // {link : "antiquities", name : "Antiquities"},
    // {link : "unlimited-edition", name : "Unlimited Edition"},
    // {link : "collectors-edition", name : "Collector's Edition"},
    // {link : "international-edition", name : "International Edition"},
    // {link : "beta-edition", name : "Beta Edition"},
    // {link : "alpha-edition", name : "Alpha Edition"},
    // {link : "born-of-the-gods", name : "Born of the Gods"},
    // {link : "magic-2014-m14", name : "Magic 2014 (M14)"},
    // {link : "dragons-maze", name : "Dragon's Maze"},
    // {link : "magic-2013-m13", name : "Magic 2013 (M13)"},
    // {link : "avacyn-restored", name : "Avacyn Restored"},
    // {link : "dark-ascension", name : "Dark Ascension"},
    // {link : "innistrad", name : "Innistrad"},
    // {link : "magic-2012-m12", name : "Magic 2012 (M12)"},
    // {link : "new-phyrexia", name : "New Phyrexia"},
    // {link : "mirrodin-besieged", name : "Mirrodin Besieged"},
    // {link : "modern-masters", name : "Modern Masters"},
    // {link : "arabian-nights", name : "Arabian Nights"},
    // {link : "commanders-arsenal", name : "Commander's Arsenal"},
    // {link : "commander-2013", name : "Commander 2013"},
    // {link : "commander", name : "Commander"},
    // {link : "planechase-2012", name : "Planechase 2012"},
    // {link : "planechase", name : "Planechase"},
    // {link : "magic-modern-event-deck", name : "Magic Modern Event Deck"},
    // {link : "conspiracy", name : "Conspiracy"},
    // {link : "duel-decks-speed-vs-cunning", name : "Duel Decks: Speed vs. Cunning"},
    // {link : "duel-decks-jace-vs-vraska", name : "Duel Decks: Jace vs. Vraska"},
    // {link : "duel-decks-heroes-vs-monsters", name : "Duel Decks: Heroes vs. Monsters"},
    // {link : "duel-decks-sorin-vs-tibalt", name : "Duel Decks: Sorin vs. Tibalt"},
    // {link : "duel-decks-izzet-vs-golgari", name : "Duel Decks: Izzet vs. Golgari"},
    // {link : "duel-decks-venser-vs-koth", name : "Duel Decks: Venser vs. Koth"},
    // {link : "duel-decks-ajani-vs-nicol-bolas", name : "Duel Decks: Ajani vs. Nicol Bolas"},
    // {link : "duel-decks-knights-vs-dragons", name : "Duel Decks: Knights vs. Dragons"},
    // {link : "duel-decks-elspeth-vs-tezzeret", name : "Duel Decks: Elspeth vs. Tezzeret"},
    // {link : "duel-decks-phyrexia-vs-the-coalition", name : "Duel Decks: Phyrexia vs. the Coalition"},
    // {link : "duel-decks-garruk-vs-liliana", name : "Duel Decks: Garruk vs. Liliana"},
    // {link : "duel-decks-divine-vs-demonic", name : "Duel Decks: Divine vs. Demonic"},
    // {link : "duel-decks-jace-vs-chandra", name : "Duel Decks: Jace vs. Chandra"},
    // {link : "duel-decks-elves-vs-goblins", name : "Duel Decks: Elves vs. Goblins"},
    // {link : "from-the-vault-annihilation", name : "From the Vault: Annihilation"},
    // {link : "from-the-vault-twenty", name : "From the Vault: Twenty"},
    // {link : "from-the-vault-realms", name : "From the Vault: Realms"},
    // {link : "from-the-vault-legends", name : "From the Vault: Legends"},
    // {link : "from-the-vault-relics", name : "From the Vault: Relics"},
    // {link : "from-the-vault-exiled", name : "From the Vault: Exiled"},
    // {link : "from-the-vault-dragons", name : "From the Vault: Dragons"},
    // {link : "premium-deck-series-graveborn", name : "Premium Deck Series: Graveborn"},
    // {link : "premium-deck-series-fire-and-lightning", name : "Premium Deck Series: Fire and Lightning"},
    // {link : "premium-deck-series-slivers", name : "Premium Deck Series: Slivers"},
    // {link : "deckmasters-garfield-vs-finkel", name : "Deckmasters Garfield vs Finkel"},
    // {link : "beatdown-box-set", name : "Beatdown Box Set"},
    // {link : "battle-royale-box-set", name : "Battle Royale Box Set"},
    // {link : "astral", name : "Astral"},
    // {link : "box-sets", name : "Box Sets"},
    // {link : "duel-decks", name : "Duel Decks"},
    // {link : "fourth-edition-foreign-black-border", name : "Fourth Edition (Foreign Black Border)"},
    // {link : "fourth-edition-foreign-white-border", name : "Fourth Edition (Foreign White Border)"},
    // {link : "revised-edition-foreign-black-border", name : "Revised Edition (Foreign Black Border)"},
    // {link : "revised-edition-foreign-white-border", name : "Revised Edition (Foreign White Border)"}
]
